# Generated by Django 6.0.4 on 2026-04-23 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10)),
                ('image', models.CharField(blank=True, default='', max_length=255)),
                ('question', models.TextField()),
                ('answers', models.JSONField()),
                ('correct', models.IntegerField()),
                ('explanation', models.TextField()),
            ],
        ),
    ]
