# Generated by Django 6.0.4 on 2026-04-23 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('max_hp', models.IntegerField(default=10000)),
                ('current_hp', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
                ('questions', models.ManyToManyField(blank=True, to='questions.question')),
            ],
        ),
    ]
