# Generated by Django 6.0.4 on 2026-04-23 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='upgrade',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
