# Generated by Django 6.0.4 on 2026-04-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0002_score_upgrade'),
    ]

    operations = [
        migrations.CreateModel(
            name='BossState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_hp', models.IntegerField(default=6200)),
                ('max_hp', models.IntegerField(default=10000)),
            ],
        ),
    ]
